### ISSUE TITLE
Algunos errores/posibles errores en la UT1

### ISSUE THREAD

**Issue by Jose-Pedro-Garcia** [jorgepz/libroResMat2#14]
¡Hola! Dejo aquí algunos comentarios de errores/ posibles errores que visualicé al leer la UT1.

Hay un pequeño error en en el último párrafo de "Condiciones de vínculo y apoyo de estructuras" (página 6), donde hay un enunciado que dice: "En la Figura 1.3b se puede ser una materialización de un vínculo ..." y debería ser "En la Figura 1.3b se puede ver una materialización de un vínculo".

Por otra parte, en el enunciado del Teorema de trabajo virtual (página 15) no se consideran las fuerzas de volumen (o masa) "b" y se deberían considerar (al menos en la formulación general, a menos que se exprese explícitamente lo contrario). Este comentario se debe a que resulta un tanto ambiguo que estas fuerzas sean consideradas en las ecuaciones de equilibrio y no en este teorema, sabiendo que es la base para la formulación variacional del problema de elasticidad lineal y su vínculo con la formulación fuerte que incluye a las ecuaciones de equilibrio en su formulación. Luego, si lo anterior es convincente, sería necesario ajustar las expresiones (1.24), (1.25) y (1.26) sumando del lado derecho de las igualdades el término "integral en sigma de ( b . w ) dV".

**Comment by jorgepz** [comment]
Muchas gracias @Jose-Pedro-Garcia ! lo corregiré en los próximos días, o sos bienvenido a editar vos mismo el archivo! en este caso el del capítulo 1 https://github.com/jorgepz/libroResMat2/blob/master/tex/chapters/Cap1_intro.tex

**Comment by Jose-Pedro-Garcia** [comment]
Ahí intenté corregir esos detalles, espero haberlo hecho bien.
Saludos!

**Comment by jorgepz** [comment]
Excelente @Jose-Pedro-Garcia en https://github.com/jorgepz/libroResMat2/compare/master...Jose-Pedro-Garcia:libroResMat2:patch-1 deberías ver un botón con "create pull request" dale nomás

**Comment by jorgepz** [comment]
esta corrección ya quedó en el nuevo release. gracias @Jose-Pedro-Garcia !
