### ISSUE TITLE
Errores de tipeo en UT2

### ISSUE THREAD

**Issue by Jose-Pedro-Garcia** [jorgepz/libroResMat2#17]
¡Hola! Dejo por aquí un recopilado de lo que parecen ser errores de tipeo en la UT2.

El primero es al final de la subsección "Ecuación de rigidez" (en la sección 2.2) donde se dice que el grado de indeterminación cinemática gk fue introducido en la Unidad Temática 1 y en realidad fue al inicio de esta Unidad Temática, por lo que habría que cambiar el "1" por un "2" o bien por "introducido al incio de la Unidad Temática 2" al final del enunciado.

Por otra parte, hay otro error de tipeo en el enunciado del ejemplo de método de los desplazamientos (sección 2.2.5) donde dice: "(...) Para la fuerxa aplicada P = 10 kN, se dese determinar desplazamientos y solicitaciones de la estructura. Utilizando el método de los desplazamientos matricial". 

Por último, puede que haya un pequeño error (posiblemente al transcribirlo) en la solucción del ejercicio 2.3, publicada en la sección B.2, explícitamente en el valor de la directa de la bara AB, donde en la tabla dice que es 15,68 kN y en realidad es 15,58 kN. Esto último sería mejor que fuera corroborado con alguna herramientas más precisa que ftool o que la deducción manual, ya que por mi cuenta llegué a los mismos resultdos mostrados en la tabla corresponiente savlo esta discrepancia con la diecta en AB.

**Comment by jorgepz** [comment]
Muchas gracias @Jose-Pedro-Garcia . nuevamente si querés lo podés intentar corregir vos o en las próximas semanas lo arreglaré yo.
saludos
